import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Let's build Google with Next.js and Tailwindcss</h1>
    </div>
  );
}
